export const AccountStatus = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  SUSPENDED: 'SUSPENDED'
});

export const OtpPurpose = Object.freeze({
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD'
});

export const ResponseCode = Object.freeze({
  SUCCESS: 0,
  ADDITIONAL: 1,
  FAIL: -1,
  AUTH_INVALID_CREDENTIALS: 10,
  AUTH_UNAUTHORIZED: 11,
  AUTH_NOT_FOUND: 12,
  AUTH_EMAIL_NOT_VERIFIED: 13,
  AUTH_ACCOUNT_DISABLED: 14,
  AUTH_OTP_INVALID: 15,
  AUTH_OTP_EXPIRED: 16,
  AUTH_OTP_ATTEMPTS_EXCEEDED: 17,
  AUTH_OTP_RATE_LIMITED: 18,
  AUTH_EMAIL_ALREADY_REGISTERED: 19,
  AUTH_REFRESH_TOKEN_REUSED: 20,
  AUTH_SESSION_EXPIRED: 21,
  AUTH_ACCOUNT_SUSPENDED: 22,
  VALIDATION_ERROR: 30,
  EMAIL_SEND_ERROR: 31,
  SYSTEM_ERROR: 32
});

export const ResponseMsg = Object.freeze({ SUCCESS: 'success', ADDITIONAL: 'additional', FAIL: 'fail' });
export const NextAction = Object.freeze({ VERIFY_EMAIL: 'VERIFY_EMAIL', LOGIN: 'LOGIN' });
