export const LEARNING_DATA_SOURCE = Symbol('LEARNING_DATA_SOURCE');
export const PLACEMENT_REPOSITORY = Symbol('PLACEMENT_REPOSITORY');
export const CONTENT_GRPC_CLIENT = 'CONTENT_GRPC_CLIENT';
export const CONTENT_CLIENT = Symbol('CONTENT_CLIENT');
